### ISSUE TITLE
Mac version isn't working.... now computer crashes when i plug in the makefun nanoV3

### ISSUE THREAD

**Issue by bmellman** [emakefun/emakefun-nano-kit#1]
Hello, I installed your CH34XUSB-SERIAL_for_mac.7z

and now when i have my computer running, and i plug in the nano, my computer crashes.

How do i get your files off my computer?

thank you

**Comment by emakefun** [comment]
I ‘m so sorry ,i did not have apple computer before. 
when i get this issue from your messege . i borrow an apple computer and fix this bug  on this commit "ec3bda5b9dc43f392f744c61132678f1b5345fbf"
thank you feedback.
ken@emakefun.com

**Comment by emakefun** [comment]
ec3bda5b9dc43f392f744c61132678f1b5345fbf
update  link:
https://github.com/emakefun/emakefun-nano-kit/tree/master/CH34XUSB-SERIAL_for_mac
