### ISSUE TITLE
Can't Upload Sketch - Resource Busy

### ISSUE THREAD

**Issue by ndreisg** [emakefun/emakefun-nano-kit#3]
Hi!

When I try to upload a sketch to the Arduino Nano with my Macbook I get the following error:

`avrdude: ser_open(): can't open device "/dev/cu.usbserial-1410": Resource busy`

I found some tips on stackoverflow (create /var/lock directory, check for other processes blocking the port with `lsof`, disable csrutil, use newer driver version 1.5) but unfortunately none of them could solve my problem.

I also tried with a Debian system, but that didn't work either.

I tried to use another USB cable to make sure the delivered cable isn't broken, but that also din't help.

Is there something else I can try, or did I miss something?

Regards 
Alex

**Verbose Output:**
```
avrdude: Version 6.3-20171130
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/alex/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbserial-1410
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
avrdude: ser_open(): can't open device "/dev/cu.usbserial-1410": Resource busy
```

**Comment by VladSuciu76** [comment]
@ndreisg Any luck with the issue?

**Comment by ndreisg** [comment]
Yes. I switched processor to "ATmega328P (Old Bootloader)" in Arduino IDE.

**Comment by emakefun** [comment]
IDE version bigger than 1.8.5 need use old bootloader
